# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - projbezpieczenstwo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_9ef3a727c4ef4bbea2f9bcf5d4fee317 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_968c794bd85a4af88574580972eb3e41 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_9ef3a727c4ef4bbea2f9bcf5d4fee317 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'projbezpieczenstwo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a0efc17959324a5bb8b9c7ced3b18bf9 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_9ef3a727c4ef4bbea2f9bcf5d4fee317 }}/appsvc/staticsite:${{ github.sha }}'